"""empty message

Revision ID: 4b4a43c16af
Revises: 11ea77decb90
Create Date: 2016-10-19 13:21:19.160567

"""

# revision identifiers, used by Alembic.
revision = '4b4a43c16af'
down_revision = '11ea77decb90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
